<a href="https://colab.research.google.com/github/XJTellez/Scientific--Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy: Creación y manipulación de datos numéricos

In [ ]:
import numpy as np

### Definir un vector

```
vector=np.array([[elemento1],[elemento2],[elemento3]])
vector=np.array([elemento1,elemento2,elemento3])
```

La manera más fácil de crear un arreglo es convertir a partir de una lista predeterminada usando el comando `array`.

In [ ]:
vector1=np.array([3, 33, 333])*4
print(vector1)

vector2=np.array([1, 2, 3, 4], dtype='float32')
print(vector2)

[  12  132 1332]
[1. 2. 3. 4.]


### Definir una matriz
Ahora definamos un arreglo bidimensional, algo parecido a una matriz: ahora tenemos renglones y columnas. 

De igual manera podemos definirlo de igual manera con el comando `array` y una serie de listas que seran interpretadas como las filas de nuestros arreglos
```
matriz=np.array([
  [elemento1],[elemento2],[elemento3],
  [elemento1],[elemento2],[elemento3]
])
```

In [ ]:
#Arreglo bidimensional
matriz=np.array([[11,12,13],[21,22,23]])
print(matriz)
print()

[[11 12 13]
 [21 22 23]]



In [ ]:
# Matriz con elementos aleatorios
np.random.randint(10, size=(3, 4))

array([[0, 8, 3, 6],
       [6, 4, 0, 3],
       [6, 9, 6, 1]])

In [ ]:
# Creamos unos arreglo para unas pruebas
A=np.arange(10)
print(A)
B=np.arange(2,12)
print(B)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11]


### Dimensión de vector o matriz

```
np.shape(vector)
np.shape(matriz)
```

In [ ]:
# Método shape 
print(vector1)
print(vector1.shape)

[  12  132 1332]
(3,)


In [ ]:
# Método shape 
print(matriz)
print(matriz.shape)

[[11 12 13]
 [21 22 23]]
(2, 3)


In [ ]:
# Método size
print(vector1.size)

3


In [ ]:
# Método size
print(matriz.size)

6


In [ ]:
print(vector1.ndim)
print(matriz.ndim)

1
2


In [ ]:
# De igual manera podemos comparar los elementos de un array y usar el resultado para filtrar 

#Seleccionamos a todos los pares
a5b=matrix_int % 2==0
print('Arreglo de valores boleanos')
print(a5b)
print()

#Arreglo de los valores dados por el filtro
a5=matrix_int[a5b]
print(a5)

Arreglo de valores boleanos
[False False  True  True  True  True False  True  True False  True False
 False  True False  True False  True False  True  True False  True False
  True False  True False False  True False False False  True  True  True
  True  True  True  True False  True  True False  True False False  True
 False  True  True  True False  True False False  True  True  True  True
 False False  True  True False  True  True False  True  True False False
 False  True False  True  True  True  True  True False  True  True  True
 False  True False False  True  True  True  True  True  True False  True
 False False False  True]

[352 832 874  70   4 764 246  78 126 634 734 530 508  70 360 212 196   2
 686 650 936 328 810 112 158  42 798 750 664 776  88 602 318 926 154  18
 982 770 644 404 684 866 366  74  76 980 546 572 338  40 900 536 916 578
  20 348 510 348 600]


### Producto Punto
```
vector.dot(vector)
```

In [ ]:
arreglo.dot(arreglo)

1791792

In [ ]:
matriz.dot(arreglo)

array([19032, 33792])

In [ ]:
A1 = np.array([[1,1],[1,1]])
A2 = np.array([[2,2],[2,2]])

print('A1=')
print(A1)
print()
print('A2=')
print(A2)

A1=
[[1 1]
 [1 1]]

A2=
[[2 2]
 [2 2]]


## Operaciones Básicas

### Ejercicios de vectores

Instrucciones define los dos siguientes conjuntos de vectores y realiza las siguientes operaciones:

$\vec{v}_1 = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}, \vec{v}_2 = \begin{pmatrix} 2 \\ -1 \\ -1 \end{pmatrix}, \vec{v}_3 = \begin{pmatrix} 1 \\ -2 \\ -1 \end{pmatrix}$


$\vec{w}_1 = \begin{pmatrix} 3 \\ 5 \\ 1 \end{pmatrix} , \vec{w}_2 = \begin{pmatrix} 0 \\ 2 \\ -1 \end{pmatrix} ,\vec{w}_3 = \begin{pmatrix} 1 \\ 0 \\ 4 \end{pmatrix} $

1. Suma
2. Resta
3. Multiplicación por un escalar
4. Producto punto 

In [ ]:
v1=np.array([[1],[2],[3]])
v2=np.array([[2],[-1],[-1]])
v3=np.array([[1],[-2],[-1]])
w1=np.array([[3],[5],[1]])
w2=np.array([[0],[2],[-1]])
w3=np.array([[1],[0],[4]])

In [ ]:
print(np.sum(v1))

print('Suma horizontalmente',np.sum(v1,axis=0))
print()
print('Suma verticalmente',np.sum(v1,axis=1))

6
Suma horizontalmente [6]

Suma verticalmente [1 2 3]


### Ejercicios de matrices


Instrucciones define los dos siguientes conjuntos de vectores y realiza las siguientes operaciones:

\begin{equation*}
A = 
\begin{pmatrix}
0 & 7 & 3 & 5 \\
1 & 0 & 2 & 4 \\
6 & 2 & 5 & 0
\end{pmatrix}
\end{equation*}

\begin{equation*}
B = 
\begin{bmatrix}
7 & 2 & 9 & 3 \\
2 & 4 & 1 & 1 \\
5 & 4 & 3 & 3 \\
\end{bmatrix}
\end{equation*}

1. Suma
2. Resta
3. Multiplicación por un escalar
4. Producto de matrices
5. Transponer la matriz A

In [ ]:
A = np.array([
    [0,7,3,5],
    [1,0,2,4],
    [6,2,5,0]
])
B = np.array([
    [7,2,9,3],
    [2,4,1,1],
    [5,4,3,3]
])
print(A,"\n\n", B)

[[0 7 3 5]
 [1 0 2 4]
 [6 2 5 0]] 

 [[7 2 9 3]
 [2 4 1 1]
 [5 4 3 3]]


In [ ]:
A*B

array([[ 0, 14, 27, 15],
       [ 2,  0,  2,  4],
       [30,  8, 15,  0]])

In [ ]:
B*A

array([[ 0, 14, 27, 15],
       [ 2,  0,  2,  4],
       [30,  8, 15,  0]])

## Matrices especiales

#### Matriz Identidad
En la multiplicación en álgebra el 1 es el elemento neutro del producto. En álgebra lineal (matrices) la matriz identidad es el elemento neutro en la multiplicaicón de matrices, es decir:
```
A = matriz
I = matriz identidad 
```
$$ A * I = A $$
Donde la matriz identidad debe tener el mismo número de filas y columnas (cuadrada). Compuesta con 0 en toda la matriz, con excepción de diagonal principal que tendrá 1.

In [ ]:
matriz_cuadrada = np.random.randint(1, 10, 16).reshape(4,4)
rows = matriz_cuadrada.shape[0]
print(matriz_cuadrada)
I = np.eye(rows,dtype=np.int16)
I

[[1 4 3 2]
 [3 1 2 7]
 [8 6 1 2]
 [6 7 3 1]]


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [ ]:
np.dot(matriz_cuadrada,I)

array([[1, 4, 3, 2],
       [3, 1, 2, 7],
       [8, 6, 1, 2],
       [6, 7, 3, 1]])

In [ ]:
matriz_cuadrada @ I

array([[1, 4, 3, 2],
       [3, 1, 2, 7],
       [8, 6, 1, 2],
       [6, 7, 3, 1]])

In [ ]:
matriz_cuadrada * I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### Matriz inversa
¿Recuerdas el concepto del recíproco o inverso de un número x (no nulo)? Se  denota como:

$$f(x)^{-1} = \frac{1}{x}$$

Este número si lo multiplicamos por x da 1 como resultado.
$$ \frac{1}{x} * x = 1$$

Algo similar sucede con la inversa de una matriz. El cual se cálcula utilizando la matriz identidad. Al tener una matriz A, la matriz inversa de A, que se representa como 
$$A^{-1}$$ 
y
$$ A * A^{-1}  = I $$ 
Por lo que esta matriz es la recíproca de A.

**Nota 1**: la matriz debe ser cuadrada.

**Nota 2**: Tener en cuenta que esta matriz inversa en muchos casos **puede no existir**.En este caso se dice que la matriz es singular o degenerada. Una matriz es singular si y solo si su determinante es nulo.

In [ ]:
matriz_cuadrada_inversa = np.linalg.inv(matriz_cuadrada)
matriz_cuadrada_inversa

array([[-0.6,  0.2, -0.3,  0.6],
       [ 0.9, -0.3,  0.7, -0.9],
       [-0.9,  0.3, -1. ,  1.3],
       [ 0.4,  0. ,  0.3, -0.5]])

In [ ]:
matriz_cuadrada

array([[1, 4, 3, 2],
       [3, 1, 2, 7],
       [8, 6, 1, 2],
       [6, 7, 3, 1]])

In [ ]:
matriz_identidad = matriz_cuadrada_inversa.dot(matriz_cuadrada)
matriz_identidad.round(decimals=1)

array([[ 1., -0., -0., -0.],
       [-0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  1.]])

#### Determinante de una matriz
Número que se calcula como la suma de los productos de las diagonales de la matriz en una dirección menos la suma de los productos de las diagonales en la otra dirección.
$$|A|$$

In [ ]:
np.linalg.det(matriz_cuadrada)

15475806.00000002

#### Matriz transpuesta
Aquella en que las filas se transforman en columnas y las columnas en filas. Se representa con el símbolo A⊺
$$A^T$$

In [ ]:
np.transpose(matriz_cuadrada)

array([[10, 92, 93, 29],
       [25, 56, 93, 89],
       [73, 94, 60, 12],
       [43, 66, 15, 16]])

## Explorando más Funciones Básica en NumPy

In [ ]:
# Media del arreglo
matriz = np.random.randint(10, size=6).reshape(2,3)
a1=np.mean(matriz)
print(a1)
print()

# Media de cada una de las filas 
a2=np.mean(matriz,axis=1)
print(a2)
print()

# Mediana del arreglo
a3=np.median(matriz)
print(a3)
print()

# Desviación estándar del arreglo 
a4=np.std(matriz)
print(a4)

4.666666666666667

[5.333333333 4.         ]

4.0

2.6246692913372702


In [ ]:
# Máximo valor en el arreglo
print('Maximo=',np.amax(matriz))


# Minimo valor en el arreglo 
print('Mínimo=',np.amin(matriz))

# Rango del Arreglo -> R= max(A)-min(A)
print('Rango=',np.ptp(matriz))


Maximo= 9
Mínimo= 2
Rango= 7


### Orden 


In [ ]:
# create a 10 element array of randoms
desord = np.random.randn(10)

print(desord)

[-0.895547703  1.05697263   0.288890459 -1.734783933 -0.24730777
  2.091793597  1.174744153  0.291956027  0.638910228  1.916188501]


In [ ]:
# Encontrando valores únicas

arreglo = np.array([1,2,1,4,2,1,4,2])

print(np.unique(arreglo))

[1 2 4]


In [ ]:
# Crear una copia y ordenarla 
ord = np.array(desord)
ord.sort()

print('Desordenados')
print(desord)
print()
print('Ordenados')
print(ord)

Desordenados
[-0.895547703  1.05697263   0.288890459 -1.734783933 -0.24730777
  2.091793597  1.174744153  0.291956027  0.638910228  1.916188501]

Ordenados
[-1.734783933 -0.895547703 -0.24730777   0.288890459  0.291956027
  0.638910228  1.05697263   1.174744153  1.916188501  2.091793597]


In [ ]:
# Obtener los indices que ordenerian el arreglo
ind=desord.argsort()
print('Indices: ',ind)

# Colocamos los indices para que se ordenen 
print(desord[ind])



Indices:  [3 0 4 2 7 8 1 6 9 5]
[-1.734783933 -0.895547703 -0.24730777   0.288890459  0.291956027
  0.638910228  1.05697263   1.174744153  1.916188501  2.091793597]


### Forma 
reshape
transpose 
vstack 
hstack 
contatenados 
ravle 



In [ ]:
# Creamos un arreglo unidimensional de 0 al 19
arr = np.arange(20)
print('Original')
print(arr)
print()

# Le cambiamos la forma para que sea un arreglo de 4 x 5 
print('Reacomodo')
ARR=arr.reshape(4,5)
print(ARR)

Original
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reacomodo
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Transposición: cambio de columnas por filas y viceversa
print(ARR.T)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [ ]:
# Aplanamos el arreglo de dos dimensiones para que sea de nuevo de uno
print(np.ravel(ARR))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#Creamos dos arreglos de 2 dimensiones que solo contengan enteros aleatoriamente 
K = np.random.randint(low=2,high=50,size=(2,2))
print('K=')
print(K)
print()
print('M=')
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

K=
[[43 11]
 [42 34]]

M=
[[21 27]
 [12 20]]


In [ ]:
# Concatenación vertical

#Forma 1
VS=np.vstack((K,M))

#Forma 2 
VS2=np.concatenate([K, M], axis = 0)


print('Concatenado vertical')
print(VS)
print()
print(VS2)

Concatenado vertical
[[43 11]
 [42 34]
 [21 27]
 [12 20]]

[[43 11]
 [42 34]
 [21 27]
 [12 20]]


In [ ]:
# Concatenación horizontal

#Forma 1
VH=np.hstack((K,M))

#Forma 2 
VH2=np.concatenate([K, M.T], axis = 1)

print('Concatenado horizontal')
print(VH)
print()
print(VH2)

Concatenado horizontal
[[43 11 21 27]
 [42 34 12 20]]

[[43 11 21 12]
 [42 34 27 20]]


### Broadcasting 

Una de las ventajas que nos ofrece numpy es poder operar elementos de arreglos de diferentes tamaños y esto se llama broadcasting. 


In [ ]:
A = np.zeros((4,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Suma en cada fila los elementos del vector 

print('Vector renglon VR',np.array([2,4,1]))
print()
print('Operacion A+VR ')
print(A+np.array([2,3,1]))
print()


#Ahora suma las columnas
print('Vector columna VC')
print(np.array([[2],[3],[1],[0]]))
print()
print('Operacion A+VC ')
print(A+np.array([[2],[3],[1],[0]]))


Vector renglon VR [2 4 1]

Operacion A+VR 
[[2. 3. 1.]
 [2. 3. 1.]
 [2. 3. 1.]
 [2. 3. 1.]]

Vector columna VC
[[2]
 [3]
 [1]
 [0]]

Operacion A+VC 
[[2. 2. 2.]
 [3. 3. 3.]
 [1. 1. 1.]
 [0. 0. 0.]]


### Funciones universales
 
 Son todas aquellas funciones típicas encontradas en las operaciones matemáticas
 
* **Operaciones matemáticas básicas:**  Suma de elementos, producto de elementos, redondeo, divisiones, logaritmos, raices, exponentes, signo, etc.  

* **Funciones tringonométricas:** seno, coseno, tangente, funciones hiperbólicas, etc

* **Funciones lógicas:** and, or, xor, not, etc. 

* **Comparaciones: **  mayor que, menor que, igual que, etc. 
  


In [ ]:
#Funcion suma 
# sum vs np.sum
print('sum(A) ',np.sum(matriz))

sum(A)  28


In [ ]:
large_array = np.random.randint(1, 100, size=1000000)

In [ ]:
%timeit sum(large_array)

10 loops, best of 3: 167 ms per loop


In [ ]:
%timeit np.sum(large_array)

1000 loops, best of 3: 705 µs per loop


In [ ]:
#Función add
print('np.add(A,B)=', np.add(matriz,matriz))
print()

#Función seno
print('np.sin(A)=', np.sin(A))
print()

np.add(A,B)= [[10 18  4]
 [14  6  4]]

np.sin(A)= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



### Generadores de números aleatorios




In [ ]:
#Arreglos de números aleatorios uniformemente distribuidos
W=np.random.uniform(size=4)
print(W)

[0.8677121  0.20096911 0.59803366 0.10539127]


In [ ]:
# Arreglos de números aleatorios normalmente distribuidos
Y = np.random.normal(size = (3,5))
print(Y)

[[-0.94272735 -0.04521501 -0.39305939 -0.13281634 -0.06200822]
 [-0.64042656  0.71570884  1.98049744 -0.30834497 -0.64711113]
 [-0.4426638  -0.68713849 -0.34417704 -0.48252396  1.23359879]]


In [ ]:
# Arreglos de números enteros aleatorios 
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[39  9 44 36]


In [ ]:
# Permutación para de un arreglo 
print(np.random.permutation(Z))

[44 36  9 39]


### Leer datos de un archivo

In [ ]:
vector_txt = np.genfromtxt("https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/iris/iris.csv", delimiter=",")
vector_txt[1:,:4]

In [ ]:
vector_txt.shape

(151, 5)